import Head from 'next/head';
import { Button } from '@dudoong/ui';
import useSample from '@lib/hooks/useSample';
import { useRouter } from 'next/router';

const LandingPage = () => {
  const a = useSample();
  const router = useRouter();
  return (
    <>
      <Head>
        <title>두둥!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        티켓 레포 보일러플레이트
        <Button
          onClick={() => {
            router.push('/home');
          }}
        >
          홈으로
        </Button>
      </main>
    </>
  );
};

export default LandingPage;
