<<<<<<< HEAD
import { authState } from '@store/auth';
import Head from 'next/head';
<<<<<<< HEAD:apps/ticket/src/pages/index.tsx
=======
import Head from 'next/head';
>>>>>>> 063ebb69fddd847a3cd56de3b0a400154246fa22
import { Button } from '@dudoong/ui';
import useSample from '@lib/hooks/useSample';
import { useRouter } from 'next/router';

const LandingPage = () => {
  const a = useSample();
  const router = useRouter();
<<<<<<< HEAD
=======
import { useRecoilState } from 'recoil';

const HomePage = () => {
  const [value] = useRecoilState(authState);
>>>>>>> 063ebb69fddd847a3cd56de3b0a400154246fa22:apps/ticket/src/pages/home/index.tsx
  return (
    <>
      <Head>
        <title>두둥! | 홈</title>
=======
  return (
    <>
      <Head>
        <title>두둥!</title>
>>>>>>> 063ebb69fddd847a3cd56de3b0a400154246fa22
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<<<<<<< HEAD
<<<<<<< HEAD:apps/ticket/src/pages/index.tsx
      <main>
        티켓 레포 보일러플레이트
        <Button
=======
      <main>
        티켓 레포 보일러플레이트
        <Button
          css={{ backgroundColor: 'yellow' }}
>>>>>>> 063ebb69fddd847a3cd56de3b0a400154246fa22
          onClick={() => {
            router.push('/home');
          }}
        >
          홈으로
        </Button>
      </main>
<<<<<<< HEAD
=======
      homepage
>>>>>>> 063ebb69fddd847a3cd56de3b0a400154246fa22:apps/ticket/src/pages/home/index.tsx
=======
>>>>>>> 063ebb69fddd847a3cd56de3b0a400154246fa22
    </>
  );
};

<<<<<<< HEAD
<<<<<<< HEAD:apps/ticket/src/pages/index.tsx
export default LandingPage;
=======
export default HomePage;
>>>>>>> 063ebb69fddd847a3cd56de3b0a400154246fa22:apps/ticket/src/pages/home/index.tsx
=======
export default LandingPage;
>>>>>>> 063ebb69fddd847a3cd56de3b0a400154246fa22
