FROM node:16-alpine AS builder

# 작업 디렉토리 설정
WORKDIR /app

# package.json 및 yarn.lock 파일 복사
COPY package.json ./
COPY yarn.lock ./

# Yarn을 최신 버전으로 업그레이드
RUN npm install yarn@3.3.0 --global --force

# 의존성 설치
RUN yarn install --immutable --immutable-cache --check-cache

# 애플리케이션 소스 복사
COPY . ./

# 필요없는 디렉토리 제거
RUN rm -rf apps/admin

# 앱 빌드
RUN yarn ticket:build

# 캐시 제거
RUN rm -rf apps/ticket/.next/cache

EXPOSE 3000

CMD ["yarn", "ticket:start"]
