import { authState } from '@store/auth';
import Head from 'next/head';
import { useRecoilState } from 'recoil';

const HomePage = () => {
  const [value] = useRecoilState(authState);
  return (
    <>
      <Head>
        <title>두둥! | 홈</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      homepage
    </>
  );
};

export default HomePage;
