import Head from 'next/head';

const HomePage = () => {
  return (
    <>
      <Head>
        <title>두둥! | 홈</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>티켓 홈</main>
    </>
  );
};

export default HomePage;
